- name: Install Nginx on RedHat/CentOS/Amazon Linux
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Create frontend directory
  file:
    path: /var/www/frontend
    state: directory
    owner: nginx     # or root if you prefer
    group: nginx
    mode: '0755'

- name: Copy frontend build
  copy:
    src: ./front/
    dest: /var/www/frontend/
    owner: nginx
    group: nginx
    mode: '0644'
    

- name: Remove default Nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Configure Nginx reverse proxy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/frontend
    mode: '0644'

- name: Enable frontend site
  file:
    src: /etc/nginx/sites-available/frontend
    dest: /etc/nginx/sites-enabled/frontend
    state: link

- name: Test Nginx config
  command: nginx -t
  register: nginx_test
  changed_when: false

- name: Reload Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
