---
- name: Retrieve RDS credentials (local or CI)
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  vars:
    secret_name: "teachua-db-password"
    region: "us-east-1"
    role_arn: "arn:aws:iam::135424146100:role/TerraformExecutionRole"
    profile: "terraform-user"

  tasks:
    - name: Check if AWS creds already in ENV (CI case)
      set_fact:
        creds_in_env: >-
          {{ lookup('env', 'AWS_ACCESS_KEY_ID') != '' and
             lookup('env', 'AWS_SECRET_ACCESS_KEY') != '' }}

    - name: Assume role to get temporary credentials (local case)
      amazon.aws.sts_assume_role:
        profile: "{{ profile }}"
        role_arn: "{{ role_arn }}"
        role_session_name: "mysession"
      register: assumed_role
      when: not creds_in_env

    - name: Lookup secret from AWS Secrets Manager
      set_fact:
        db_secret: >-
          {{ lookup(
               'amazon.aws.aws_secret',
               secret_name,
               region=region,
               access_key=(assumed_role.sts_creds.access_key if not creds_in_env else lookup('env', 'AWS_ACCESS_KEY_ID')),
               secret_key=(assumed_role.sts_creds.secret_key if not creds_in_env else lookup('env', 'AWS_SECRET_ACCESS_KEY')),
               session_token=(assumed_role.sts_creds.session_token if not creds_in_env else lookup('env', 'AWS_SESSION_TOKEN'))
             )
          }}

    - name: Debug DB secret content
      debug:
        var: db_secret

    - name: Save DB credentials for next play
      set_fact:
        db_user: "teachua_user"
        db_pass: "{{ db_secret }}"
        db_name: "teachua"


- name: Load initial MariaDB data from backend VM
  hosts: backend
  become: yes
  vars:
    db_user: "{{ hostvars['localhost'].db_user }}"
    db_pass: "{{ hostvars['localhost'].db_pass }}"
    db_host: "{{ database_endpoint.split(':')[0] }}"
    db_port: "{{ database_endpoint.split(':')[1] }}"
    db_name: "{{ hostvars['localhost'].db_name }}"

  tasks:
    - name: Show DB host
      debug:
        var: db_host

    - name: Show DB user
      debug:
        var: db_user

    - name: Show DB password
      debug:
        var: db_pass

    - name: Show DB port
      debug:
        var: db_port

    - name: Load schema
      community.mysql.mysql_db:
        state: import
        name: "{{ db_name }}"
        login_host: "{{ db_host }}"
        #login_port: "{{ db_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"
        target: "/opt/app/init.sql"
        restrict_config_file: true

    - name: Load initial data
      community.mysql.mysql_db:
        state: import
        name: "{{ db_name }}"
        login_host: "{{ db_host }}"
        login_port: "{{ db_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_pass }}"
        target: "/opt/app/data.sql"
