- hosts: backend
  roles:
    - role: proxy_env
      vars:
        http_proxy: "http://{{ bastion_private_ip }}:3128"
        https_proxy: "http://{{ bastion_private_ip }}:3128"
        no_proxy: "localhost,127.0.0.1,10.0.0.0/8"
