name: Full CI/CD Pipeline
on:
  push:
    branches:
      - feature/terraform-aws-without-nat
  workflow_dispatch:
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Terraform state file
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: terraform-teachua/
        continue-on-error: true  # in case this is first run and no artifact yet

      - name: Terraform Init
        run: |
          cd terraform-teachua
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform-teachua
          terraform plan  -var="key_pair_name=${{ secrets.KEY_PAIR_NAME }}"

      - name: Terraform Apply
        run: |
          cd terraform-teachua
          terraform apply -auto-approve -var="key_pair_name=${{ secrets.KEY_PAIR_NAME }}"
          continue-on-error: true

      - name: Upload Terraform state file
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform-teachua/terraform.tfstat
