name: Full CI/CD Pipeline
on:
  push:
    branches:
      - feature/terraform-aws-without-nat
  workflow_dispatch:
jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
       steps:      - name: Download Terraform state file
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: terraform-teachua/
        continue-on-error: true  # in case this is first run and no artifact yet

      - name: Upload Terraform state file
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform-teachua/terraform.tfstate
